# Default values for ita-api-admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  itaGlobalDefinition:
    name: ita-global
    enabled: true
    image:
      registry: "docker.io"
      organization: exastro
      package: exastro-it-automation
    config:
      DEFAULT_LANGUAGE: "ja"
      LANGUAGE: "en"
      CONTAINER_BASE: "kubernetes"
      TZ: "Asia/Tokyo"
      STORAGEPATH: "/storage/"
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 10Gi
      volumeType: hostPath # e.g.) hostPath or AKS
      storageClass: "-" # e.g.) azurefile or - (None)
      # matchLabels: 
      #   release: "stable"
      # matchExpressions:
      #   - {key: environment, operator: In, values: [dev]}
  gitlabDefinition:
    name: gitlab
    enabled: true
    config:
      GITLAB_PROTOCOL: "http"
      GITLAB_HOST: "gitlab.exastro-platform.svc"
      GITLAB_PORT: "80"
    secret:
      GITLAB_ROOT_TOKEN: ""
  itaDatabaseDefinition:
    name: ita-database
    enabled: true
    config:
      DB_VENDOR: "mariadb"
      DB_HOST: "mariadb.exastro-platform.svc"
      DB_PORT: "3306"
      DB_DATADBASE: "ITA_DB"
    secret:
      DB_ROOT_PASSWORD: ""
      DB_USER: ""
      DB_PASSWORD: ""

ita-api-admin:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

ita-api-organization:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

ita-by-ansible-execute:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

ita-by-ansible-legacy-role-vars-listup:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

ita-by-ansible-towermaster-sync:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

ita-by-conductor-synchronize:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

ita-by-menu-create:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

ita-database-setup-job:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

ita-web-server:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

