apiVersion: v1
entries:
  exastro-it-automation:
  - apiVersion: v2
    appVersion: 2.0.0-beta.1
    created: "2022-10-19T00:11:52.700027861+09:00"
    description: Exastro IT Automation is an Open Source Framework for digitizing
      and centrally managing the system configuration.
    digest: 1b269161d832db858c41b99132f9f3241db0c241757046228a76437fbc5aebff
    home: https://exastro-suite.github.io/
    icon: https://exastro-suite.github.io/docs/asset/logo/exastro/Exastro-logomark2-rgb.svg
    keywords:
    - exastro
    - exastro-it-automation
    maintainers:
    - email: contact@exastro.jp.nec.com
      name: NEC Corporation
    name: exastro-it-automation
    sources:
    - https://github.com/exastro-suite/exastro-it-automation
    type: application
    urls:
    - exastro-it-automation-0.1.0.tgz
    version: 0.1.0
generated: "2022-10-19T00:11:52.691294985+09:00"
