openapi: 3.0.3
info:
  title: Exastro ITA Event Relay Reciever API
  description: Exastro ITA Event Relay Reciever API
  version: 2.1.0

servers:
  - url: "https://{host}"
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: "http://{host}"
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: "{protocol}://{host}:{port}"
    description: API endpoint (Development)
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      host:
        default: localhost
      port:
        default: '30080'

tags:
  - name: Event Relay
    description: イベント連携機能の情報を取得・登録

paths:
  /api/{organization_id}/workspaces/{workspace_id}/event_relay_agent/event_collection/settings:
    post:
      tags:
        - Event Relay
      description: 対象のイベント収集設定と最新のイベント取得時間を取得
      operationId: getEventCollectionSettings
      x-openapi-router-controller: controllers.event_relay_controller
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: 対象のイベント収集設定のUUIDを記載
              properties:
                event_collection_settings_ids:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  data:
                    type: array
                    items:
                      type: object
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

components:
  schemas:
    ERROR_TEMPLATE:
      type: object
      properties:
        result:
          type: string
          example: 001-002
        message:
          type: string

  securitySchemes:
    BearerAuth:
      description: Credentials or access token for API
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      description: Value converted from ID/Password in base64
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
security:
- BearerAuth: []
- BasicAuth: []
