openapi: 3.0.3
info:
  title: Exastro ITA Event Relay Reciever API
  description: Exastro ITA Event Relay Reciever API
  version: 2.1.0
servers:
- url: "https://{host}"
  description: API endpoint
  variables:
    host:
      default: localhost
- url: "http://{host}"
  description: API endpoint
  variables:
    host:
      default: localhost
- url: "{protocol}://{host}:{port}"
  description: API endpoint (Development)
  variables:
    protocol:
      default: https
      enum:
      - http
      - https
    host:
      default: localhost
    port:
      default: "30080"
tags:
- name: Event Relay
  description: イベント連携機能の情報を取得・登録
paths:
  /api/{organization_id}/workspaces/{workspace_id}/event_relay_agent/event_collection/settings:
    post:
      tags:
      - Event Relay
      description: 対象のイベント収集設定と最新のイベント取得時間を取得
      operationId: post_event_collection_settings
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/event_collection_settings_body'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.event_relay_controller
components:
  schemas:
    ERROR_TEMPLATE:
      type: object
      properties:
        result:
          type: string
          example: 001-002
        message:
          type: string
    event_collection_settings_body:
      properties:
        event_collection_settings_ids:
          type: array
          items:
            type: string
      description: 対象のイベント収集設定のUUIDを記載
    inline_response_200:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          type: array
          items:
            type: object
        message:
          type: string
      example:
        result: 000-00000
        data:
        - {}
        - {}
        message: message
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  securitySchemes:
    BearerAuth:
      type: http
      description: Credentials or access token for API
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: swagger_server.controllers.authorization_controller.check_BearerAuth
    BasicAuth:
      type: http
      description: Value converted from ID/Password in base64
      scheme: basic
      x-basicInfoFunc: swagger_server.controllers.authorization_controller.check_BasicAuth

